#!/usr/bin/env python3
"""
Seed all investment prompts into the database
"""
import os
import ssl
import json
import asyncio
import uuid
from datetime import datetime

DATABASE_URL = os.environ.get('DATABASE_URL')

PROMPTS = [
    # IDEA GENERATION (10 prompts)
    {"name": "thematic_candidate_screen", "category": "idea_generation", "subcategory": "thematic", "description": "Identifies investment candidates based on a specific investment theme", "template": "You are a senior equity research analyst specializing in thematic investing. Given the investment theme: {{theme}}\n\nYour task is to:\n1. Define the theme precisely and identify its key drivers\n2. Map the value chain and ecosystem participants\n3. Identify 10-15 publicly traded companies with significant exposure to this theme\n4. For each company, assess:\n   - Revenue exposure to the theme (% of total revenue)\n   - Competitive positioning within the theme\n   - Growth trajectory related to the theme\n   - Valuation relative to theme peers\n\nPrioritize pure play companies with >50% revenue exposure over diversified conglomerates.\nOutput a ranked list with investment rationale for each candidate.", "variables": {"theme": "string"}, "source": "wall_street_prompts"},
    {"name": "institutional_clustering_13f", "category": "idea_generation", "subcategory": "institutional", "description": "Analyzes 13F filings to find stocks where top institutional investors are clustering", "template": "You are an institutional research analyst specializing in 13F filing analysis.\n\nAnalyze the following 13F data for {{quarter}}:\n{{filing_data}}\n\nYour task is to:\n1. Identify stocks where 3+ top-tier institutions have initiated or increased positions\n2. Calculate the aggregate position change across all filers\n3. Identify any unusual concentration patterns\n4. Cross-reference with recent price action and fundamentals\n5. Flag any potential crowded trades with risk assessment\n\nProvide a ranked list of the most compelling clustering signals with conviction scores.", "variables": {"quarter": "string", "filing_data": "json"}, "source": "wall_street_prompts"},
    {"name": "insider_trading_signals", "category": "idea_generation", "subcategory": "insider", "description": "Analyzes insider buying/selling patterns for investment signals", "template": "You are a compliance-aware analyst specializing in Form 4 insider transaction analysis.\n\nAnalyze the following insider transactions for {{ticker}}:\n{{transaction_data}}\n\nEvaluate:\n1. Net insider buying/selling over the past 3, 6, and 12 months\n2. Quality of insiders transacting (CEO/CFO vs. directors)\n3. Transaction sizes relative to compensation and holdings\n4. Timing relative to earnings and material events\n5. Historical accuracy of this company insider signals\n\nProvide a signal strength rating (1-10) with detailed rationale.", "variables": {"ticker": "string", "transaction_data": "json"}, "source": "wall_street_prompts"},
    {"name": "trend_to_equity_mapper", "category": "idea_generation", "subcategory": "trend_analysis", "description": "Maps emerging trends to equity investment opportunities", "template": "You are a cross-disciplinary analyst connecting macro trends to equity opportunities.\n\nAnalyze the following trend: {{trend_description}}\n\nYour task is to:\n1. Validate the trend with supporting data points\n2. Estimate the trend duration and growth trajectory\n3. Map the trend to specific industries and sectors\n4. Identify 5-10 publicly traded beneficiaries\n5. Assess each company leverage to the trend\n6. Identify potential losers/disrupted companies\n\nProvide actionable investment recommendations with time horizons.", "variables": {"trend_description": "string"}, "source": "notion_investing_library"},
    {"name": "newsletter_idea_extractor", "category": "idea_generation", "subcategory": "alternative_sources", "description": "Extracts and analyzes investment ideas from financial newsletters", "template": "You are an investment analyst extracting ideas from financial publications.\n\nAnalyze the following newsletter content:\n{{newsletter_content}}\n\nFor each investment idea mentioned:\n1. Identify the ticker symbol and company name\n2. Summarize the investment thesis in 2-3 sentences\n3. Extract key data points and metrics cited\n4. Identify the time horizon (short/medium/long term)\n5. Note any price targets or valuation metrics\n6. Assess the quality and track record of the source\n\nOutput a structured list of actionable ideas with confidence scores.", "variables": {"newsletter_content": "string"}, "source": "wall_street_prompts"},
    {"name": "social_sentiment_scanner", "category": "idea_generation", "subcategory": "alternative_data", "description": "Analyzes social media sentiment for investment signals", "template": "You are a quantitative analyst specializing in alternative data.\n\nAnalyze social media sentiment for {{ticker}} or {{topic}}:\n{{social_data}}\n\nYour analysis should:\n1. Calculate sentiment scores across platforms (Twitter, Reddit, StockTwits)\n2. Identify key opinion leaders and their positions\n3. Track sentiment momentum and inflection points\n4. Separate retail noise from informed commentary\n5. Cross-reference with price action and volume\n6. Flag potential manipulation or coordinated activity\n\nProvide a sentiment signal with confidence interval.", "variables": {"ticker": "string", "topic": "string", "social_data": "json"}, "source": "notion_investing_library"},
    {"name": "sector_rotation_analyzer", "category": "idea_generation", "subcategory": "macro", "description": "Identifies sector rotation opportunities based on economic cycle", "template": "You are a macro strategist analyzing sector rotation opportunities.\n\nCurrent economic indicators:\n{{economic_data}}\n\nYour task is to:\n1. Determine the current phase of the economic cycle\n2. Identify sectors historically outperforming in this phase\n3. Analyze relative strength and momentum across sectors\n4. Identify specific ETFs and stocks for positioning\n5. Set entry/exit triggers based on leading indicators\n6. Define risk management parameters\n\nProvide specific sector allocation recommendations with rationale.", "variables": {"economic_data": "json"}, "source": "wall_street_prompts"},
    {"name": "value_chain_mapper", "category": "idea_generation", "subcategory": "industry_analysis", "description": "Maps industry value chains to find investment opportunities", "template": "You are an industry analyst mapping value chains for investment opportunities.\n\nIndustry: {{industry}}\nFocus Company (optional): {{focus_company}}\n\nYour task is to:\n1. Map the complete value chain from raw materials to end consumers\n2. Identify key players at each stage\n3. Analyze margin profiles and competitive dynamics at each level\n4. Identify bottlenecks and pricing power nodes\n5. Find undervalued or overlooked participants\n6. Assess vertical integration trends\n\nProvide investment recommendations across the value chain.", "variables": {"industry": "string", "focus_company": "string"}, "source": "notion_investing_library"},
    {"name": "pure_play_filter", "category": "idea_generation", "subcategory": "thematic", "description": "Filters for companies with pure-play exposure to specific themes", "template": "You are a thematic analyst filtering for pure-play exposure.\n\nTheme: {{theme}}\nCandidate Companies: {{candidates}}\n\nFor each candidate, analyze:\n1. Revenue breakdown by segment\n2. Percentage of revenue directly tied to theme\n3. Management commentary on theme exposure\n4. Capital allocation toward theme-related initiatives\n5. Competitive positioning within the theme\n\nRank companies by purity of exposure (>70% = pure play, 50-70% = significant, <50% = diversified).\nRecommend the top 5 pure plays with investment thesis.", "variables": {"theme": "string", "candidates": "list"}, "source": "wall_street_prompts"},
    {"name": "historical_parallel_finder", "category": "idea_generation", "subcategory": "pattern_recognition", "description": "Finds historical parallels to stress-test investment theses", "template": "You are a market historian analyzing historical parallels.\n\nCurrent Situation: {{situation}}\nInvestment Thesis: {{thesis}}\n\nYour task is to:\n1. Identify 3-5 historical situations with similar characteristics\n2. Analyze how those situations resolved\n3. Map outcomes to the current thesis\n4. Identify key differences that might change outcomes\n5. Calculate base rates for thesis success/failure\n6. Recommend adjustments to the thesis based on historical evidence\n\nProvide probability-weighted scenario analysis.", "variables": {"situation": "string", "thesis": "string"}, "source": "notion_investing_library"},
    # DUE DILIGENCE (10 prompts)
    {"name": "financial_statement_deep_dive", "category": "due_diligence", "subcategory": "financial_analysis", "description": "Comprehensive financial statement analysis", "template": "You are a senior financial analyst conducting deep financial statement analysis.\n\nCompany: {{ticker}}\nFinancial Data: {{financial_data}}\n\nAnalyze:\n1. Revenue quality and sustainability\n2. Margin trends and drivers\n3. Working capital efficiency\n4. Cash flow quality vs. reported earnings\n5. Balance sheet strength and leverage\n6. Capital allocation track record\n7. Accounting red flags or aggressive policies\n\nProvide a financial health score (1-100) with detailed breakdown.", "variables": {"ticker": "string", "financial_data": "json"}, "source": "wall_street_prompts"},
    {"name": "competitive_moat_assessment", "category": "due_diligence", "subcategory": "competitive_analysis", "description": "Assesses the durability of competitive advantages", "template": "You are a strategic analyst assessing competitive moats.\n\nCompany: {{ticker}}\nIndustry Context: {{industry_data}}\n\nEvaluate the following moat sources:\n1. Network effects (strength and defensibility)\n2. Switching costs (customer lock-in)\n3. Cost advantages (scale, process, location)\n4. Intangible assets (brands, patents, licenses)\n5. Efficient scale (natural monopoly characteristics)\n\nFor each moat source:\n- Rate strength (1-10)\n- Assess durability (years)\n- Identify threats\n\nProvide an overall moat rating with investment implications.", "variables": {"ticker": "string", "industry_data": "json"}, "source": "wall_street_prompts"},
    {"name": "dcf_model_builder", "category": "due_diligence", "subcategory": "valuation", "description": "Builds comprehensive DCF valuation model", "template": "You are a valuation specialist building a DCF model.\n\nCompany: {{ticker}}\nHistorical Financials: {{historical_data}}\nGuidance/Estimates: {{estimates}}\n\nBuild a 10-year DCF model with:\n1. Revenue growth assumptions (justify each year)\n2. Margin trajectory to steady state\n3. Working capital and capex requirements\n4. WACC calculation with component breakdown\n5. Terminal value using both perpetuity and exit multiple\n6. Sensitivity analysis on key assumptions\n\nProvide fair value range with probability-weighted scenarios.", "variables": {"ticker": "string", "historical_data": "json", "estimates": "json"}, "source": "wall_street_prompts"},
    {"name": "management_quality_assessment", "category": "due_diligence", "subcategory": "qualitative", "description": "Assesses management team quality and track record", "template": "You are an analyst evaluating management quality.\n\nCompany: {{ticker}}\nManagement Team: {{management_data}}\nHistorical Performance: {{performance_data}}\n\nEvaluate:\n1. Track record of value creation\n2. Capital allocation decisions\n3. Compensation alignment with shareholders\n4. Communication quality and transparency\n5. Insider ownership and transactions\n6. Succession planning\n7. Cultural indicators\n\nProvide a management quality score (1-10) with detailed rationale.", "variables": {"ticker": "string", "management_data": "json", "performance_data": "json"}, "source": "notion_investing_library"},
    {"name": "earnings_quality_analyzer", "category": "due_diligence", "subcategory": "financial_analysis", "description": "Analyzes the quality and sustainability of earnings", "template": "You are a forensic accountant analyzing earnings quality.\n\nCompany: {{ticker}}\nFinancial Statements: {{financial_data}}\n\nAnalyze:\n1. Accruals ratio and trend\n2. Cash conversion quality\n3. Revenue recognition policies\n4. Expense capitalization practices\n5. Off-balance sheet items\n6. Related party transactions\n7. Audit quality indicators\n\nProvide an earnings quality score (1-100) with red flags highlighted.", "variables": {"ticker": "string", "financial_data": "json"}, "source": "wall_street_prompts"},
    {"name": "risk_factor_identifier", "category": "due_diligence", "subcategory": "risk_analysis", "description": "Identifies and quantifies investment risks", "template": "You are a risk analyst identifying investment risks.\n\nCompany: {{ticker}}\nBusiness Description: {{business_data}}\n10-K Risk Factors: {{risk_factors}}\n\nCategorize and assess risks:\n1. Business/operational risks\n2. Financial/leverage risks\n3. Regulatory/legal risks\n4. Competitive risks\n5. Macro/cyclical risks\n6. ESG risks\n\nFor each risk:\n- Probability of occurrence\n- Potential impact on value\n- Mitigation factors\n\nProvide a risk-adjusted investment recommendation.", "variables": {"ticker": "string", "business_data": "json", "risk_factors": "string"}, "source": "notion_investing_library"},
    {"name": "comparable_company_analysis", "category": "due_diligence", "subcategory": "valuation", "description": "Performs comprehensive comparable company analysis", "template": "You are a valuation analyst performing comps analysis.\n\nTarget Company: {{ticker}}\nPeer Set: {{peers}}\n\nAnalyze:\n1. Select appropriate peer group with justification\n2. Calculate relevant multiples (EV/Revenue, EV/EBITDA, P/E, etc.)\n3. Adjust for differences in growth, margins, risk\n4. Identify outliers and explain\n5. Determine appropriate multiple range for target\n6. Calculate implied valuation range\n\nProvide a fair value estimate with confidence interval.", "variables": {"ticker": "string", "peers": "list"}, "source": "wall_street_prompts"},
    {"name": "tam_sam_som_analyzer", "category": "due_diligence", "subcategory": "market_analysis", "description": "Analyzes total addressable market and market share potential", "template": "You are a market analyst sizing the opportunity.\n\nCompany: {{ticker}}\nMarket Data: {{market_data}}\n\nAnalyze:\n1. Total Addressable Market (TAM) - top-down and bottom-up\n2. Serviceable Addressable Market (SAM)\n3. Serviceable Obtainable Market (SOM)\n4. Current market share and trajectory\n5. Market growth drivers and inhibitors\n6. Competitive intensity and share dynamics\n\nProvide market opportunity assessment with revenue implications.", "variables": {"ticker": "string", "market_data": "json"}, "source": "notion_investing_library"},
    {"name": "unit_economics_analyzer", "category": "due_diligence", "subcategory": "financial_analysis", "description": "Analyzes unit economics and profitability drivers", "template": "You are a financial analyst examining unit economics.\n\nCompany: {{ticker}}\nUnit Data: {{unit_data}}\n\nAnalyze:\n1. Customer acquisition cost (CAC)\n2. Lifetime value (LTV)\n3. LTV/CAC ratio and trend\n4. Payback period\n5. Gross margin per unit\n6. Contribution margin\n7. Path to profitability at scale\n\nProvide assessment of business model sustainability.", "variables": {"ticker": "string", "unit_data": "json"}, "source": "wall_street_prompts"},
    {"name": "capital_structure_optimizer", "category": "due_diligence", "subcategory": "financial_analysis", "description": "Analyzes and optimizes capital structure", "template": "You are a corporate finance specialist analyzing capital structure.\n\nCompany: {{ticker}}\nBalance Sheet: {{balance_sheet}}\nDebt Details: {{debt_data}}\n\nAnalyze:\n1. Current leverage ratios vs. peers\n2. Debt maturity profile\n3. Interest coverage and debt service\n4. Credit rating implications\n5. Optimal capital structure\n6. Refinancing opportunities\n7. Capital return capacity\n\nProvide recommendations for capital structure optimization.", "variables": {"ticker": "string", "balance_sheet": "json", "debt_data": "json"}, "source": "notion_investing_library"},
    # PORTFOLIO MANAGEMENT (5 prompts)
    {"name": "portfolio_risk_analyzer", "category": "portfolio_management", "subcategory": "risk", "description": "Analyzes portfolio risk metrics and exposures", "template": "You are a portfolio risk manager analyzing risk exposures.\n\nPortfolio Holdings: {{holdings}}\nMarket Data: {{market_data}}\n\nAnalyze:\n1. Portfolio beta and volatility\n2. Sector/factor exposures\n3. Concentration risk\n4. Correlation analysis\n5. Value at Risk (VaR)\n6. Stress test scenarios\n7. Tail risk assessment\n\nProvide risk report with recommendations for risk reduction.", "variables": {"holdings": "json", "market_data": "json"}, "source": "wall_street_prompts"},
    {"name": "position_sizer", "category": "portfolio_management", "subcategory": "sizing", "description": "Determines optimal position sizes based on conviction and risk", "template": "You are a portfolio manager determining position sizes.\n\nInvestment Opportunity: {{opportunity}}\nPortfolio Context: {{portfolio}}\nRisk Parameters: {{risk_params}}\n\nDetermine:\n1. Conviction level (1-10)\n2. Risk/reward ratio\n3. Correlation with existing holdings\n4. Liquidity constraints\n5. Optimal position size\n6. Scaling strategy (entry/exit)\n\nProvide position sizing recommendation with rationale.", "variables": {"opportunity": "json", "portfolio": "json", "risk_params": "json"}, "source": "notion_investing_library"},
    {"name": "rebalancing_optimizer", "category": "portfolio_management", "subcategory": "rebalancing", "description": "Optimizes portfolio rebalancing decisions", "template": "You are a portfolio manager optimizing rebalancing.\n\nCurrent Portfolio: {{current_portfolio}}\nTarget Allocation: {{target_allocation}}\nConstraints: {{constraints}}\n\nOptimize:\n1. Drift from target allocation\n2. Tax implications of trades\n3. Transaction costs\n4. Timing considerations\n5. Rebalancing trades\n6. Implementation schedule\n\nProvide rebalancing plan with trade list.", "variables": {"current_portfolio": "json", "target_allocation": "json", "constraints": "json"}, "source": "wall_street_prompts"},
    {"name": "factor_exposure_analyzer", "category": "portfolio_management", "subcategory": "factor_analysis", "description": "Analyzes portfolio factor exposures", "template": "You are a quantitative analyst analyzing factor exposures.\n\nPortfolio: {{portfolio}}\nFactor Data: {{factor_data}}\n\nAnalyze exposures to:\n1. Value (P/E, P/B, FCF yield)\n2. Momentum (price, earnings)\n3. Quality (ROE, margins, stability)\n4. Size (market cap)\n5. Volatility (beta, vol)\n6. Growth (revenue, earnings growth)\n\nProvide factor attribution and recommendations.", "variables": {"portfolio": "json", "factor_data": "json"}, "source": "notion_investing_library"},
    {"name": "correlation_monitor", "category": "portfolio_management", "subcategory": "risk", "description": "Monitors and analyzes portfolio correlations", "template": "You are a risk analyst monitoring correlations.\n\nPortfolio: {{portfolio}}\nHistorical Returns: {{returns_data}}\n\nAnalyze:\n1. Pairwise correlations\n2. Correlation clustering\n3. Regime-dependent correlations\n4. Correlation breakdown risk\n5. Diversification benefit\n6. Hidden factor exposures\n\nProvide correlation report with diversification recommendations.", "variables": {"portfolio": "json", "returns_data": "json"}, "source": "wall_street_prompts"},
    # MARKET ANALYSIS (5 prompts)
    {"name": "market_regime_classifier", "category": "market_analysis", "subcategory": "regime", "description": "Classifies current market regime", "template": "You are a macro strategist classifying market regimes.\n\nMarket Data: {{market_data}}\nEconomic Indicators: {{economic_data}}\n\nClassify the current regime:\n1. Growth/inflation quadrant\n2. Risk-on vs. risk-off\n3. Volatility regime\n4. Credit cycle phase\n5. Liquidity conditions\n6. Sentiment indicators\n\nProvide regime classification with asset allocation implications.", "variables": {"market_data": "json", "economic_data": "json"}, "source": "wall_street_prompts"},
    {"name": "earnings_season_analyzer", "category": "market_analysis", "subcategory": "earnings", "description": "Analyzes earnings season trends and surprises", "template": "You are an earnings analyst tracking earnings season.\n\nEarnings Data: {{earnings_data}}\nSector: {{sector}}\n\nAnalyze:\n1. Beat/miss rates vs. historical\n2. Revision trends\n3. Guidance patterns\n4. Margin commentary themes\n5. Sector-specific trends\n6. Forward implications\n\nProvide earnings season summary with investment implications.", "variables": {"earnings_data": "json", "sector": "string"}, "source": "notion_investing_library"},
    {"name": "fed_policy_analyzer", "category": "market_analysis", "subcategory": "macro", "description": "Analyzes Federal Reserve policy and implications", "template": "You are a macro strategist analyzing Fed policy.\n\nFed Communications: {{fed_data}}\nEconomic Data: {{economic_data}}\n\nAnalyze:\n1. Current policy stance\n2. Forward guidance interpretation\n3. Dot plot analysis\n4. Balance sheet trajectory\n5. Market pricing vs. Fed guidance\n6. Historical policy parallels\n\nProvide Fed policy outlook with market implications.", "variables": {"fed_data": "json", "economic_data": "json"}, "source": "wall_street_prompts"},
    {"name": "sector_momentum_ranker", "category": "market_analysis", "subcategory": "technical", "description": "Ranks sectors by momentum and relative strength", "template": "You are a technical analyst ranking sector momentum.\n\nSector Data: {{sector_data}}\nTime Period: {{period}}\n\nAnalyze:\n1. Absolute momentum (3m, 6m, 12m)\n2. Relative strength vs. SPY\n3. Breadth indicators\n4. Volume trends\n5. Technical patterns\n6. Rotation signals\n\nProvide sector rankings with rotation recommendations.", "variables": {"sector_data": "json", "period": "string"}, "source": "notion_investing_library"},
    {"name": "volatility_surface_analyzer", "category": "market_analysis", "subcategory": "options", "description": "Analyzes options volatility surface", "template": "You are a volatility analyst examining the vol surface.\n\nOptions Data: {{options_data}}\nUnderlying: {{ticker}}\n\nAnalyze:\n1. ATM implied volatility\n2. Skew (put vs. call)\n3. Term structure\n4. Historical vs. implied vol\n5. Volatility risk premium\n6. Event vol pricing\n\nProvide volatility analysis with trading implications.", "variables": {"options_data": "json", "ticker": "string"}, "source": "wall_street_prompts"},
    # RESEARCH SYNTHESIS (5 prompts)
    {"name": "investment_thesis_builder", "category": "research_synthesis", "subcategory": "thesis", "description": "Builds comprehensive investment thesis", "template": "You are a senior analyst building an investment thesis.\n\nCompany: {{ticker}}\nResearch Inputs: {{research_data}}\n\nBuild a thesis covering:\n1. Investment summary (2-3 sentences)\n2. Key investment merits (3-5 points)\n3. Key risks (3-5 points)\n4. Valuation and price target\n5. Catalysts and timeline\n6. Position sizing recommendation\n\nProvide a complete investment thesis document.", "variables": {"ticker": "string", "research_data": "json"}, "source": "wall_street_prompts"},
    {"name": "bull_bear_case_generator", "category": "research_synthesis", "subcategory": "scenario", "description": "Generates bull and bear cases for investment", "template": "You are an analyst generating bull/bear scenarios.\n\nCompany: {{ticker}}\nBase Case: {{base_case}}\n\nGenerate:\n1. Bull case scenario\n   - Key assumptions\n   - Probability\n   - Price target\n2. Bear case scenario\n   - Key assumptions\n   - Probability\n   - Price target\n3. Key swing factors\n4. Monitoring triggers\n\nProvide probability-weighted expected value.", "variables": {"ticker": "string", "base_case": "json"}, "source": "notion_investing_library"},
    {"name": "research_note_generator", "category": "research_synthesis", "subcategory": "documentation", "description": "Generates professional research notes", "template": "You are a research analyst writing a note.\n\nCompany: {{ticker}}\nEvent/Topic: {{topic}}\nAnalysis: {{analysis}}\n\nGenerate a research note with:\n1. Executive summary\n2. Key takeaways (bullet points)\n3. Detailed analysis\n4. Valuation update\n5. Recommendation\n6. Risks to thesis\n\nFormat as a professional research note.", "variables": {"ticker": "string", "topic": "string", "analysis": "json"}, "source": "wall_street_prompts"},
    {"name": "earnings_preview_generator", "category": "research_synthesis", "subcategory": "earnings", "description": "Generates earnings preview reports", "template": "You are an analyst preparing an earnings preview.\n\nCompany: {{ticker}}\nConsensus Estimates: {{estimates}}\nHistorical Data: {{historical}}\n\nGenerate preview covering:\n1. Key metrics to watch\n2. Consensus expectations\n3. Whisper numbers\n4. Key questions for management\n5. Potential surprises\n6. Stock reaction scenarios\n\nProvide actionable trading guidance.", "variables": {"ticker": "string", "estimates": "json", "historical": "json"}, "source": "notion_investing_library"},
    {"name": "conference_call_analyzer", "category": "research_synthesis", "subcategory": "qualitative", "description": "Analyzes earnings conference call transcripts", "template": "You are an analyst reviewing a conference call.\n\nTranscript: {{transcript}}\nPrevious Call: {{previous_call}}\n\nAnalyze:\n1. Key themes and tone changes\n2. Management confidence level\n3. Guidance changes and language\n4. Analyst question patterns\n5. Red flags or positive signals\n6. Action items for follow-up\n\nProvide call summary with investment implications.", "variables": {"transcript": "string", "previous_call": "string"}, "source": "wall_street_prompts"},
    # MONITORING (4 prompts)
    {"name": "thesis_tracker", "category": "monitoring", "subcategory": "thesis", "description": "Tracks investment thesis progress", "template": "You are monitoring an investment thesis.\n\nOriginal Thesis: {{thesis}}\nCurrent Data: {{current_data}}\nPosition: {{position}}\n\nTrack:\n1. Thesis milestones achieved\n2. Thesis risks materialized\n3. Valuation vs. target\n4. Catalyst timeline\n5. Position performance\n6. Thesis integrity score\n\nProvide thesis update with action recommendations.", "variables": {"thesis": "json", "current_data": "json", "position": "json"}, "source": "wall_street_prompts"},
    {"name": "news_sentiment_monitor", "category": "monitoring", "subcategory": "news", "description": "Monitors news flow and sentiment", "template": "You are monitoring news flow for a position.\n\nCompany: {{ticker}}\nNews Feed: {{news_data}}\nThesis: {{thesis}}\n\nMonitor:\n1. Material news events\n2. Sentiment shifts\n3. Competitor developments\n4. Regulatory updates\n5. Management changes\n6. Thesis-relevant signals\n\nProvide news digest with action alerts.", "variables": {"ticker": "string", "news_data": "json", "thesis": "json"}, "source": "notion_investing_library"},
    {"name": "price_alert_analyzer", "category": "monitoring", "subcategory": "technical", "description": "Analyzes price movements and triggers", "template": "You are analyzing a price alert.\n\nTicker: {{ticker}}\nAlert Trigger: {{alert}}\nPrice Action: {{price_data}}\n\nAnalyze:\n1. Cause of price movement\n2. Volume analysis\n3. Technical significance\n4. News correlation\n5. Thesis impact\n6. Action recommendation\n\nProvide alert analysis with next steps.", "variables": {"ticker": "string", "alert": "json", "price_data": "json"}, "source": "wall_street_prompts"},
    {"name": "portfolio_performance_reporter", "category": "monitoring", "subcategory": "performance", "description": "Generates portfolio performance reports", "template": "You are generating a performance report.\n\nPortfolio: {{portfolio}}\nPeriod: {{period}}\nBenchmark: {{benchmark}}\n\nReport:\n1. Total return vs. benchmark\n2. Attribution analysis\n3. Best/worst performers\n4. Risk metrics\n5. Factor contributions\n6. Key decisions impact\n\nProvide comprehensive performance report.", "variables": {"portfolio": "json", "period": "string", "benchmark": "string"}, "source": "notion_investing_library"},
    # SPECIAL SITUATIONS (5 prompts)
    {"name": "merger_arbitrage_analyzer", "category": "special_situations", "subcategory": "ma", "description": "Analyzes merger arbitrage opportunities", "template": "You are a special situations analyst evaluating merger arb.\n\nDeal: {{deal_details}}\nMarket Data: {{market_data}}\n\nAnalyze:\n1. Deal terms and structure\n2. Regulatory risk assessment\n3. Financing conditions\n4. Spread analysis\n5. Timeline and milestones\n6. Downside scenario\n\nProvide risk/reward assessment with position recommendation.", "variables": {"deal_details": "json", "market_data": "json"}, "source": "wall_street_prompts"},
    {"name": "activist_situation_analyzer", "category": "special_situations", "subcategory": "activism", "description": "Analyzes activist investor situations", "template": "You are analyzing an activist situation.\n\nTarget: {{ticker}}\nActivist: {{activist}}\n13D Filing: {{filing_data}}\n\nAnalyze:\n1. Activist track record\n2. Campaign objectives\n3. Board/management response\n4. Likely outcomes\n5. Timeline expectations\n6. Value creation potential\n\nProvide investment recommendation.", "variables": {"ticker": "string", "activist": "string", "filing_data": "json"}, "source": "notion_investing_library"},
    {"name": "distressed_debt_analyzer", "category": "special_situations", "subcategory": "distressed", "description": "Analyzes distressed debt opportunities", "template": "You are a distressed debt analyst.\n\nCompany: {{ticker}}\nDebt Structure: {{debt_data}}\nFinancials: {{financials}}\n\nAnalyze:\n1. Liquidity runway\n2. Capital structure priority\n3. Recovery analysis\n4. Restructuring scenarios\n5. Fulcrum security\n6. Risk/reward by tranche\n\nProvide distressed investment recommendation.", "variables": {"ticker": "string", "debt_data": "json", "financials": "json"}, "source": "wall_street_prompts"},
    {"name": "ipo_analysis", "category": "special_situations", "subcategory": "ipo", "description": "Analyzes IPO investment opportunities", "template": "You are an IPO analyst evaluating a new issue.\n\nCompany: {{company}}\nS-1 Data: {{s1_data}}\nComparables: {{comps}}\n\nAnalyze:\n1. Business model and moat\n2. Growth trajectory\n3. Profitability path\n4. Valuation vs. comps\n5. Use of proceeds\n6. Lock-up dynamics\n\nProvide IPO investment recommendation.", "variables": {"company": "string", "s1_data": "json", "comps": "json"}, "source": "notion_investing_library"},
    {"name": "spinoff_opportunity_analyzer", "category": "special_situations", "subcategory": "corporate_actions", "description": "Analyzes spinoff investment opportunities", "template": "You are a special situations analyst evaluating spinoffs.\n\nParent Company: {{parent_ticker}}\nSpinoff Details: {{spinoff_details}}\n\nAnalyze:\n1. Strategic rationale for separation\n2. Standalone valuation of spinoff\n3. Forced selling dynamics\n4. Index inclusion/exclusion impact\n5. Management incentive alignment\n6. Hidden value unlocking potential\n\nProvide investment recommendation for both parent and spinoff.", "variables": {"parent_ticker": "string", "spinoff_details": "json"}, "source": "notion_investing_library"}
]

async def seed_prompts():
    import asyncpg
    from urllib.parse import urlparse
    
    url = DATABASE_URL
    parsed = urlparse(url)
    
    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    
    conn = await asyncpg.connect(
        host=parsed.hostname,
        port=parsed.port or 25060,
        user=parsed.username,
        password=parsed.password,
        database=parsed.path.lstrip('/'),
        ssl=ssl_context
    )
    
    print(f"Connected. Seeding {len(PROMPTS)} prompts...")
    
    inserted = 0
    for prompt in PROMPTS:
        try:
            await conn.execute('''
                INSERT INTO prompt_templates (id, name, category, subcategory, description, template, variables, source, version, is_active, usage_count, created_at, updated_at)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
                ON CONFLICT (name) DO UPDATE SET
                    template = EXCLUDED.template,
                    description = EXCLUDED.description,
                    updated_at = EXCLUDED.updated_at
            ''',
                str(uuid.uuid4()),
                prompt['name'],
                prompt['category'],
                prompt.get('subcategory'),
                prompt.get('description'),
                prompt['template'],
                json.dumps(prompt.get('variables', {})),
                prompt.get('source', 'system'),
                1,
                True,
                0,
                datetime.utcnow(),
                datetime.utcnow()
            )
            inserted += 1
            print(f"  + {prompt['name']}")
        except Exception as e:
            print(f"  x {prompt['name']}: {e}")
    
    await conn.close()
    print(f"\nSeeded {inserted}/{len(PROMPTS)} prompts!")

if __name__ == "__main__":
    asyncio.run(seed_prompts())
